# Generated by Django 2.1 on 2019-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190304_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_in_category', to='webapp.Category', verbose_name='Категория'),
        ),
    ]
