# Generated by Django 2.1 on 2019-03-07 06:06

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190306_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=webapp.models.generate_code, editable=False, max_length=6, unique_for_date='created_date', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renew_date',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка'),
        ),
    ]
